
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int ELSE = 25;
  public static final int cadena_texto = 29;
  public static final int expr = 7;
  public static final int WHILE = 26;
  public static final int Labre = 19;
  public static final int $ = 28;
  public static final int pot = 12;
  public static final int por = 10;
  public static final int Lcierra = 20;
  public static final int SWITCH = 6;
  public static final int IF = 24;
  public static final int or = 17;
  public static final int num = 3;
  public static final int puts = 27;
  public static final int menos = 9;
  public static final int menor = 15;
  public static final int set = 23;
  public static final int div = 11;
  public static final int EOF = 0;
  public static final int Cabre = 21;
  public static final int dist = 14;
  public static final int error = 1;
  public static final int comentario = 2;
  public static final int incr = 5;
  public static final int mas = 8;
  public static final int comp = 13;
  public static final int FOR = 4;
  public static final int Cciera = 22;
  public static final int and = 18;
  public static final int identificador = 30;
  public static final int mayor = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comentario",
  "num",
  "FOR",
  "incr",
  "SWITCH",
  "expr",
  "mas",
  "menos",
  "por",
  "div",
  "pot",
  "comp",
  "dist",
  "menor",
  "mayor",
  "or",
  "and",
  "Labre",
  "Lcierra",
  "Cabre",
  "Cciera",
  "set",
  "IF",
  "ELSE",
  "WHILE",
  "puts",
  "$",
  "cadena_texto",
  "identificador"
  };
}

